### ISSUE TITLE
大佬，能不能加一个修改字体的配置项，可以引入其他字体

### ISSUE THREAD

**Issue by Einstein-schrodinger** [kasuie/remio-home#1]

**Comment by kasuie** [comment]
没问题，不出意外这周

**Comment by kasuie** [comment]
> _No description provided._

可查看[该配置项](https://github.com/kasuie/remio-home?tab=readme-ov-file#GlobalStyle-%E7%B1%BB%E5%9E%8B%E8%AF%B4%E6%98%8E)
